version: 2.1

orbs:
  android: circleci/android@2.3

jobs:
  build:
    docker:
      - image: cimg/android:2023.03-browsers  
    parallelism: 4
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: |
            if [ $(circleci tests split --total 2 --index 0) ]; then
              ./gradlew lint
            else
              ./gradlew test
            fi
      - store_test_results:
          path: app/build/test-results
      - store_test_results:
          path: core/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
      - store_artifacts:
          path: core/build/reports
          destination: core-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
